# Generated by Django 5.1.2 on 2025-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('occupied', 'Occupied')], default='active', max_length=10),
        ),
    ]
