# Generated by Django 5.1.2 on 2025-05-16 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_failed_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_enabled',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
