version: '3.8'

services:
  web:
    build: .
    container_name: metrotrip_web
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "5432:5432"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: metrotrip_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: metrotrip_db
      POSTGRES_USER: metrotrip_user
      POSTGRES_PASSWORD: parkwood2702

volumes:
  postgres_data:
