version: '3.8'

services:
  web:
    build: .
    container_name: metrotrip_web
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8001:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Для доступа к хосту