version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - app_network

  web:
    build:
      context: ./Django_command
      dockerfile: Dockerfile
    container_name: command_project_container
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./Django_command:/app
      - ./Django_command/db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"
    command: watchmedo auto-restart --recursive --pattern="*.py" -- python manage.py runserver 0.0.0.0:8000
    networks:
      - app_network

volumes:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge 