version: '3.8'

services:
  web:
    build: .
    container_name: metrotrip_web
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8001:8000"  # локальный порт контейнера
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: metrotrip_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: metrotrip
      POSTGRES_USER: metrotripuser
      POSTGRES_PASSWORD: metrotrippass

volumes:
  postgres_data:
