# Generated by Django 5.0.2 on 2025-07-08 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('tech_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('годен', 'Годен'), ('брак', 'Брак')], default='годен', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_records', to='trips.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_records', to=settings.AUTH_USER_MODEL)),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_records', to='equipment.measurementtype')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
