# Generated by Django 5.1.2 on 2025-04-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_add_measurement_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrecord',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
