# Generated by Django 5.1.2 on 2025-05-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipmentrecord_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrecord',
            name='status',
            field=models.CharField(choices=[('годен', 'Годен'), ('брак', 'Брак')], default='годен', max_length=10),
        ),
    ]
