# Generated by Django 5.0.2 on 2025-07-08 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Город')),
                ('members', models.ManyToManyField(related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_trips', to=settings.AUTH_USER_MODEL, verbose_name='Старший')),
            ],
            options={
                'verbose_name': 'Командировка',
                'verbose_name_plural': 'Командировки',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='trips.businesstrip', verbose_name='Командировка')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['-created_date'],
            },
        ),
    ]
