# Generated by Django 5.0.2 on 2025-07-18 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalStaffRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(verbose_name='Неделя (дата понедельника)')),
                ('value', models.PositiveIntegerField(verbose_name='Число тех. состава')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время внесения')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_staff_records', to='trips.organization', verbose_name='Организация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Старший группы')),
            ],
            options={
                'verbose_name': 'Запись тех. состава',
                'verbose_name_plural': 'Записи тех. состава',
                'unique_together': {('organization', 'week')},
            },
        ),
    ]
