# Generated by Django 5.0.2 on 2025-07-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fixed_records',
            field=models.ManyToManyField(blank=True, related_name='fixed_organizations', to='equipment.equipmentrecord', verbose_name='Зафиксированные записи'),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_fixed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней фиксации'),
        ),
    ]
