# Generated by Django 5.0.2 on 2025-07-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_organization_fixed_records_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fixed_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Показывать фиксированные данные админу до'),
        ),
    ]
