# Generated by Django 5.1.2 on 2025-04-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstrip',
            name='is_active',
        ),
    ]
