# Generated by Django 5.0.2 on 2025-07-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_organization_fixed_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tech_staff_count',
            field=models.IntegerField(default=0, verbose_name='Тех состав (текущее значение)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tech_staff_fixed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Тех состав (зафиксированное значение)'),
        ),
    ]
