# Generated by Django 5.1.2 on 2025-04-05 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_businesstrip_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesstrip',
            options={'ordering': ['-start_date'], 'verbose_name': 'Командировка', 'verbose_name_plural': 'Командировки'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_date'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.RemoveField(
            model_name='businesstrip',
            name='city',
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='members',
            field=models.ManyToManyField(related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='senior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_trips', to=settings.AUTH_USER_MODEL, verbose_name='Старший'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыта'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='trips.businesstrip', verbose_name='Командировка'),
        ),
    ]
